### ISSUE TITLE
Messages are not received by my subscribed process when running in test env.

### ISSUE THREAD

**Issue by Primebrook** [cheerfulstoic/ecto_watch#15]
When in a test env for some reason table updates does not seem to trigger messages being sent to my genserver which is subscribed to the updates. 

My setup does work in a dev environment (although I had to run `mix ecto.reset` in my dev env for it to work?). Also I know my genserver is running successfully in the test env (the `init/1` function runs) from logs. It just seems that the `handle_info/2` function in my genserver is not being called.

**Comment by cheerfulstoic** [comment]
That's really interesting... 🤔   One of my first thoughts is that maybe there should be a `debug` option in `EctoWatch` which outputs logs to show what's working correctly (setting up the triggers, getting messages from the database, and sending out broadcasts are events that come to mind)

All that said, there is this recent issue/PR which is currently under discussion: https://github.com/cheerfulstoic/ecto_watch/pull/14

I wonder: how are you actually using `EctoWatch` in your tests?  Would it be ridiculous for you if the library just disabled the watchers in test mode?

**Comment by cheerfulstoic** [comment]
👋  Hey, curious if you're still having this issue and what you may think of the above!  There have also been a number of updates to `ecto_watch` since this issue.  They don't address it specifically, but it would be good if you tried the latest version to see how it works for you.  Make sure to check out the "Upgrading Versions" page in [the `ecto_watch` hexdocs](https://hexdocs.pm/ecto_watch/) for information about breaking changes.

**Comment by camstuart** [comment]
Not sure if it is related, but my tests are having some trouble since I added ecto watch. I run my tests like this:

`mix test --max-failures 1`

and I see:

```
15:00:02.353 [error] Postgrex.Protocol (#PID<0.286.0>) disconnected: ** (DBConnection.ConnectionError) #PID<0.94.0> checked in the connection owned by #PID<0.344.0>

#PID<0.94.0> triggered the checkin at location:

  (kernel 10.0) code_server.erl:154: :code_server.call/1
  (elixir 1.16.3) src/elixir_compiler.erl:68: :elixir_compiler.dispatch/4
  (elixir 1.16.3) src/elixir_compiler.erl:52: :elixir_compiler.compile/4
  (elixir 1.16.3) src/elixir_compiler.erl:39: :elixir_compiler.maybe_fast_compile/3
  (elixir 1.16.3) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.16.3) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.16.3) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
  (elixir 1.16.3) lib/code.ex:1489: Code.require_file/2
  
  ...

15:00:02.358 [error] Task #PID<0.344.0> started from EctoWatch terminating
** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout
  (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
  (ecto_watch 0.9.11) lib/ecto_watch/watcher_trigger_validator.ex:162: EctoWatch.WatcherTriggerValidator.sql_query/2
  (ecto_watch 0.9.11) lib/ecto_watch/watcher_trigger_validator.ex:129: EctoWatch.WatcherTriggerValidator.find_triggers/1
  (ecto_watch 0.9.11) lib/ecto_watch/watcher_trigger_validator.ex:96: anonymous fn/1 in EctoWatch.WatcherTriggerValidator.triggers_by_repo_mod/0
  (elixir 1.16.3) lib/map.ex:257: Map.do_map/2
  (elixir 1.16.3) lib/map.ex:251: Map.new_from_map/2
  (ecto_watch 0.9.11) lib/ecto_watch/watcher_trigger_validator.ex:32: EctoWatch.WatcherTriggerValidator.run/1
  (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &EctoWatch.WatcherTriggerValidator.run/1
  Args: [nil]
    
```

Related? or something else perhaps?

**Comment by cheerfulstoic** [comment]
Interesting.... Honestly I'm not sure, but it's possible 🤔  That second error is from `ecto_watch` in the the task that runs to check if there are extra triggers / functions in the database..

But when I lookup "connection is closed because of an error, disconnect or timeout" I just see a couple of places.  There's [this discussion](https://github.com/dashbitco/broadway/issues/116) with Jose Valim on the `broadway` repo.  In the end I guess there was a too-small timeout involved.  There was also [this thread](https://elixirforum.com/t/getting-timeout-on-running-ecto-migrator-with-repo-2/48813) where they increased the timeout, but I suspect increasing a timeout to 20 minutes is way too much 😅 

So I'm wondering if there is some interaction with `ecto_watch`.  Some questions:

 * Do some tests run successfully before it fails, or does this fail immediately?
 * If it doesn't fail immediately, does it fail after different numbers of tests each time you run?  Does running with a seed (e.g. `--seed=12345`) cause it to fail the same way every time?
 * Can you get it to fail by just running one test file but then it succeeds with others?

Do you have any non-standard configuration for your ecto repo?

As somebody asked in that first thread: Are you using ecto sandbox in your tests? If so are you using [allowances](https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.Sandbox.html#module-allowances) or [shared mode](https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.Sandbox.html#module-shared-mode)? Are you running tests with async: true?

Can't say I completely understand everything, but I can try to do some research based on what your configuration is

**Comment by cheerfulstoic** [comment]
FYI I just released version 0.11.0 with a `debug?` option.  You can learn more from [this HexDocs page](https://hexdocs.pm/ecto_watch/debugging.html)

**Comment by cheerfulstoic** [comment]
You might want to checkout #28 as well, by the way.  It has something to do with `ecto_watch` not running in `test`.  Not sure if it's the same 🤷

**Comment by cheerfulstoic** [comment]
Going to close for now, but feel free to re-open if it's still happening.  If it is, I'm happy to do a round of debugging, and perhaps we could jump on a call if needed
