### ISSUE TITLE
Permit watching tables without requiring schemas.

### ISSUE THREAD

**Issue by frerich** [cheerfulstoic/ecto_watch#16]
Ecto permits accessing tables even if no Ecto schema was defined, e.g.

```elixir
from(row in "students", where: row.last_name == "Smith", select: row.id)
```

It would be great if EctoWatch would support the same, i.e. passing a plain string (and an optional `:prefix` option) in the list of watchers instead of requiring a schema.

If this is deemed interesting, I'd be happy to see if I can whip up a PR.

**Comment by cheerfulstoic** [comment]
True! 🤔  Though then in a sense the "Ecto" in the name `EctoWatch` makes less sense 😅  But I don't know if I'm necessarily against this...  It's probably somewhat more complicated than you think, though.  Some things off the top of my head:

 * The library always uses the `primary_key` in messages, so that would need to be specified
 * The library looks at the ecto schema's associations (to broadcast when they are in `extra_columns` and to determine if those columns can be subscribed to, which is a new feature that was just added in 0.6.0)
 * Currently the ecto schema's module atom is used as part of the Phoenix.PubSub channel name, so maybe the table name would need to be used

Maybe something like this could be supported:

```elixir
  {EctoWatch,
   repo: MyApp.Repo,
   pub_sub: MyApp.PubSub,
   watchers: [
     {%{table: "comments", primary_key: :id, association_columns: [:post_id]}, :inserted},
   ]}

```

Though it feels like then it's starting to approach the point that having an ecto schema defined, even if just for the purpose of `EctoWatch`, would be the cleaner / more standardized approach that would keep the `ecto_watch` code cleaner.

So I'd want to first ask: what's the use-case to avoid defining an ecto schema?

**Comment by frerich** [comment]
> what's the use-case to avoid defining an ecto schema?

The database I'm dealing with exposes a view (as in `CREATE VIEW ...`) which is defined in terms of a few replicated tables. Those replicated tables are never accessed by the application directly, it always only interfaces with the view (and for the view, it does have a nice Ecto schema). My thinking was that I could use EctoWatch to get notified about changes in the raw tables and in case something happens, then access the view to read from them.

Maybe it would even be worthwhile to consider this the 'canonical' use case, i.e. a `watchers` definition like you sketched is the default and providing an Ecto schema is permitted for convenience (table names, primary keys, prefixes etc. will be derived from the schema)?

**Comment by cheerfulstoic** [comment]
Yeah, sure, that could make a lot of sense (having a standard format which is created from a schema in the current default case).  It might even simplify the code by removing the ecto-specific logic from various places... 🤔   I can play around with that 👍 

Just so that I understand, though... did you say you had an ecto schema for the views?  I guess I assume that you can have an ecto schema for views so long as you don't do any insert/update/deletes (?)

**Comment by frerich** [comment]
> Just so that I understand, though... did you say you had an ecto schema for the views? I guess I assume that you can have an ecto schema for views so long as you don't do any insert/update/deletes (?)

That's right! Any attempts to modify the view will fail, of course, but reading from it works perfectly fine.

**Comment by cheerfulstoic** [comment]
👋  I've created PR #18 to implement this and I think overall the code is cleaner because of the standardization onto a `SchemaDefinition` object and the extraction of ecto schema details early 🎉 

Perhaps you'd like to take a look and give feedback.  Maybe try pointing to the branch from your `mix.exs`?

**Comment by cheerfulstoic** [comment]
As I was working on this, by the way, I realized something that I might just change in the next version that goes out with this change...  For schemaless watchers I required the `label` option because can can't just match on the ecto schema module name when defining the table via a map.  But in general I'm realizing that if you use `label` it represents both the table and the update_type, so instead of doing:

```elixir
EctoWatch.subscribe(:user_update, :updated)

def handle_info({:updated, :user_update, %{id: id}}, socket) do
```

I think it probably makes sense to do this when using the `label` option:

```elixir
EctoWatch.subscribe(:user_update)

def handle_info({:user_update, %{id: id}}, socket) do
```

Curious if you have any thoughts there, but mainly an FYI because I think I'll probably do that soon.

**Comment by cheerfulstoic** [comment]
Haven't released this just yet!

**Comment by cheerfulstoic** [comment]
Released this a little while ago!
