### ISSUE TITLE
EctoWatch does not detect some triggers created

### ISSUE THREAD

**Issue by AdrianCDS** [cheerfulstoic/ecto_watch#35]
Whenever I run my server, or compile my application I receive these errors (however the app continues to function):

```
[error] Found the following extra EctoWatch triggers:

"ew_deleted_for_applname_db_communities_communityorganisation_tr" in the table "public"."community_organisations"

"ew_deleted_for_applname_db_organisations_organisationuser_trigg" in the table "public"."organisation_users"

"ew_inserted_for_applname_db_communities_communityorganisation_t" in the table "public"."community_organisations"

"ew_inserted_for_applname_db_organisations_organisationuser_trig" in the table "public"."organisation_users"

"ew_updated_for_applname_db_touchpoints_touchpointwebsitebanner_" in the table "public"."touchpoint_website_banners"

"ew_updated_for_applname_db_touchpoints_touchpointwebsiteurl_tri" in the table "public"."touchpoint_website_urls"

...but they were not specified in the watcher options.
```

This is how I have configured some of my watchers:

```
{EctoWatch,
    repo: Applname.Repo,
    pub_sub: Applname.PubSub,
    watchers: [
         {Touchpoint, :inserted},
         {Touchpoint, :deleted},
         {Touchpoint, :updated},
         {TouchpointWebsiteUrl, :updated},
         {TouchpointWebsiteBanner, :updated},
         {CommunityOrganisation, :inserted, extra_columns: [:community_id, :organisation_id]},
...
```

It seems that EctoWatch (upon compiling) creates triggers in the database each named like:
**ew_operationName_fullSchemaModuleName_trigger**

For example, for the first watcher in the list, the trigger generated is:
**ew_inserted_for_applname_db_touchpoints_touchpoint_trigger**

And this is recognized by EctoWatch.

But some names are generated like this:
**ew_deleted_for_applname_db_communities_communityorganisation_tr**

As you can see the name is being cut off at the end, this is because in Postgres, identifiers (such as column names, function and trigger names) have a hard limit of 64 (more exactly the NAMEDATALEN variable), resulting in 63 bytes limit for trigger names.
I checked all the triggers that appear in the error, and they all have exactly 63 characters.

I tried deleting them _manually_ from the database thinking they were leftovers after some renaming to my app, but upon compilation EctoWatch regenerated the same triggers and it's always the ones that are being cut off, so my speculation is this is the root cause of this issue. Among other issues like this one:  [https://github.com/cheerfulstoic/ecto_watch/issues/28](https://github.com/cheerfulstoic/ecto_watch/issues/28)

Another thing I tried was aliasing the module names as shorter ones like this:
`alias Applname.Db.Touchpoints.TouchpointWebsiteUrl, as: TpWebsiteUrl`

And inside the watcher's list:
 `{TpWebsiteUrl, :updated}`
 
 In hopes to get a naming like this:
 **ew_updated_for_applname_db_touchpoints_tpwebsiteurl_trigger**

But the names are still generated using the schema's module name.

This also applies to functions because I receive this error too:

```
[error] Found the following extra EctoWatch functions:

"ew_deleted_for_applname_db_communities_communityorganisation_fu" in the schema "public"
"ew_inserted_for_applname_db_communities_communityorganisation_f" in the schema "public"

...
```

Now personally, changing the NAMEDATALEN variable name, while possible, does not seem like a good choice or practice.

However, it would be really helpful if we could specify how the trigger names are generated while still being recognized by EctoWatch (but the naming based on aliasing could also might be a simpler approach), additionally it might come in handy to have a warning for this, something to detect that your triggers will fail with their default naming.

**Comment by cheerfulstoic** [comment]
Aaaahh!  Yes, that would do it 🤦 

So my first thought for a workaround: if you use the `label` option ([docs here](https://hexdocs.pm/ecto_watch/tracking-columns-and-using-labels.html)), then the trigger/function names will be based off the `label` rather than the update type+schema.

Long term, one option would be do simply require that `label` is used if the trigger/function names would be too long (via a descriptive error message).  As you point out the length is configurable in postgres (I didn't know that until just now!), so if that's the approach then a query might need to be made to get that value, if possible.

Alternatively it might be possible to auto-generate labels that fit into the length, but that might be trickier (especially if the database is configured to not be the default length, *especially* if they've configured it to be shorter than the default 😅  I also note that the postgres docs say "which can be less than 63 characters when using multibyte encodings", so that's something to pay attention to (I think the identifiers are being generated based on the table name, but I don't know if it's possible for table names to have multi-byte characters!)

I'd welcome other ideas too, but I'm curious first to verify if using the `label` option works for you for now as a workaround.

Thanks for getting back with the investigation!! ❤️ 🎉

**Comment by cheerfulstoic** [comment]
I've made a PR.  Would you like to try running the branch to see if it gives you a good enough error message?

https://github.com/cheerfulstoic/ecto_watch/pull/36/files

I didn't try to do any automatic fixing, it just won't let you start up if the function/trigger names would be too long.  If you aren't using a label it suggests that you might use a label.

The triggers look like:

```
ew_<inserted|updated|deleted>_for_<downcased schema>_trigger
# or...
ew_for_<label>_trigger
```

And the functions look like:

```
ew_<inserted|updated|deleted>_for_<downcased schema>_func
# or...
ew_for_<label>_func
```

I was thinking I might change `_trigger` to be `_trig` to make a bit more room and so the function / trigger names would always be the same length.  But this would be a breaking change that would give people errors about functions / triggers to be cleaned up (there's a tool for it in the library, so 🤷 )

**Comment by AdrianCDS** [comment]
@cheerfulstoic Thank you for the label suggestion! Must have missed this in the docs. And yes, the triggers/functions are now generated fine and the errors have disappeared.
As far as the error goes, preventing the app from starting is good enough, I personally don't think an automatic fix would be appropriate here
